version: "3.9"

services:
  backend:
    build: ./backend
    container_name: music-cloud-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - music-cloud-net
  frontend:
    build: ./frontend
    container_name: music-cloud-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - music-cloud-net
    
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: musiccloud
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  music-cloud-net:
    driver: bridge

volumes:
  db_data:
